use superconfig::{ConfigRegistry, config_flags::runtime};

fn main() {
    let registry = ConfigRegistry::new();
    
    // Test if enable_as_json method exists (should be generated by macro)
    let json_result = registry.enable_as_json(runtime::STRICT_MODE);
    println\!("✅ enable_as_json result: {}", json_result);
    
    // Test original enable method
    let registry2 = ConfigRegistry::new();
    let result = registry2.enable(runtime::STRICT_MODE).unwrap();
    println\!("✅ Original enable method works");
    println\!("✅ STRICT_MODE enabled: {}", result.runtime_enabled(runtime::STRICT_MODE));
}
EOF < /dev/null
