name: 'Setup Moon Build System'
description: 'Install Moon and Proto with caching for SuperConfig monorepo'

inputs:
  moon-version:
    description: 'Moon version to install'
    required: false
    default: '1.33.0'
  proto-version:
    description: 'Proto version to install'
    required: false
    default: '0.43.5'
  rust-version:
    description: 'Rust version to install via Proto'
    required: false
    default: 'stable'

outputs:
  cache-hit:
    description: 'Whether tools were loaded from cache'
    value: ${{ steps.tools-cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Generate cache key
      id: cache-key
      shell: bash
      run: echo "key=moon-tools-${{ runner.os }}-${{ inputs.moon-version }}-${{ inputs.proto-version }}-${{ inputs.rust-version }}" >> $GITHUB_OUTPUT

    - name: Cache Moon and Proto tools
      uses: actions/cache@v4
      id: tools-cache
      with:
        path: |
          ~/.proto
          ~/.moon
        key: ${{ steps.cache-key.outputs.key }}

    - name: Install Proto
      if: steps.tools-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -fsSL https://moonrepo.dev/install/proto.sh | bash -s -- --version ${{ inputs.proto-version }}
        echo "$HOME/.proto/bin" >> $GITHUB_PATH

    - name: Install Moon
      if: steps.tools-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        # Need to source proto in current shell for installation
        export PATH="$HOME/.proto/bin:$PATH"
        proto install moon ${{ inputs.moon-version }}

    - name: Setup PATH for cached tools
      if: steps.tools-cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "$HOME/.proto/bin" >> $GITHUB_PATH
        echo "$HOME/.moon/bin" >> $GITHUB_PATH

    - name: Install Rust toolchain
      shell: bash
      run: |
        export PATH="$HOME/.proto/bin:$PATH"
        proto install rust ${{ inputs.rust-version }}
        proto use rust ${{ inputs.rust-version }}

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ inputs.rust-version }}

    - name: Verify Moon installation
      shell: bash
      run: |
        export PATH="$HOME/.proto/bin:$HOME/.moon/bin:$PATH"
        moon --version
        proto --version